<robot name="my_move" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 控制器 -->
    <gazebo>
        <!-- https://gazebosim.org/api/sim/8/classgz_1_1sim_1_1systems_1_1DiffDrive.html -->
        <!-- <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive"> -->
        <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
            <left_joint>left_wheel2base_link</left_joint>
            <right_joint>right_wheel2base_link</right_joint>
            <wheel_separation>${base_link_radius * 2}</wheel_separation>
            <wheel_radius>${wheel_radius * 2}</wheel_radius>

            <!-- <topic>cmd_vel</topic> -->
            <!-- <odom_topic>odom</odom_topic> -->
            <!-- <tf_topic>tf</tf_topic> -->
            <!-- <frame_id>base_footprint</frame_id> -->
            <!-- <child_frame_id>odom</child_frame_id> -->

            <odom_publish_frequency>1</odom_publish_frequency>
            <max_torque>30</max_torque>
            <max_acceleration>1.8</max_acceleration>
        </plugin>
    </gazebo>

</robot>